tunnel: 64746180-e8db-4616-abfb-0433703b2645
credentials-file: /Users/juanmatute/.cloudflared/64746180-e8db-4616-abfb-0433703b2645.json

ingress:
  # Support wildcard subdomains for multi-tenancy (explicit HTTP)
  - hostname: "*.golfleaguemanager.app"
    service: http://localhost:4500
    originRequest:
      noTLSVerify: true
      httpHostHeader: localhost
  # Fallback for the main domain (explicit HTTP) 
  - hostname: golfleaguemanager.app
    service: http://localhost:4500
    originRequest:
      noTLSVerify: true
      httpHostHeader: localhost
  # Catch-all
  - service: http_status:404
