tunnel: 64746180-e8db-4616-abfb-0433703b2645
credentials-file: /etc/cloudflared/credentials.json

ingress:
  # Support wildcard subdomains for multi-tenancy
  - hostname: "*.golfleaguemanager.app"
    service: http://frontend:80
  # Fallback for the main domain
  - hostname: golfleaguemanager.app
    service: http://frontend:80
  - service: http_status:404
