tunnel: 64746180-e8db-4616-abfb-0433703b2645
credentials-file: /Users/juanmatute/.cloudflared/64746180-e8db-4616-abfb-0433703b2645.json

ingress:
  # Support wildcard subdomains for multi-tenancy
  - hostname: "*.golfleaguemanager.app"
    service: http://localhost:4500
  # Fallback for the main domain
  - hostname: golfleaguemanager.app
    service: http://localhost:4500
  - service: http_status:404
