services:
  postgres:
    image: postgres:16
    container_name: golfleague_postgres
    restart: always
    environment:
      POSTGRES_USER: golfuser
      POSTGRES_PASSWORD: golfpassword
      POSTGRES_DB: golfdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
