services:
  postgres:
    image: postgres:16
    container_name: golfleague_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: golfuser
      POSTGRES_PASSWORD: golfpassword
      POSTGRES_DB: golfdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: golfleague_backend
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=golfdb;Username=golfuser;Password=golfpassword
      - ASPNETCORE_URLS=http://+:5505
    ports:
      - "5505:5505"

  frontend:
    build:
      context: ./frontend
    container_name: golfleague_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "4500:80"

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: golfleague_cloudflared
    restart: unless-stopped
    depends_on:
      - frontend
    command: tunnel --config /etc/cloudflared/config.yml run
    volumes:
      - ./cloudflared-config.yml:/etc/cloudflared/config.yml:ro
      - ~/.cloudflared/64746180-e8db-4616-abfb-0433703b2645.json:/etc/cloudflared/credentials.json:ro
    networks:
      - default

volumes:
  postgres_data:
