name: Development Build (macOS)

on:
  push:
    branches: [ develop, feature/* ]
  pull_request:
    branches: [ develop ]

jobs:
  test-only:
    name: Test and Build Check
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Start test database
      run: |
        echo "🗄️ Starting test database for development build..."
        # Stop any existing test database
        docker stop dev-test-postgres || true
        docker rm dev-test-postgres || true
        
        # Start new test database
        docker run -d \
          --name dev-test-postgres \
          -p 5434:5432 \
          -e POSTGRES_USER=golfuser \
          -e POSTGRES_PASSWORD=golfpassword \
          -e POSTGRES_DB=golfdb_test \
          postgres:16
        
        # Wait for database to be ready (macOS compatible)
        echo "⏳ Waiting for database to be ready..."
        for i in {1..30}; do
          if docker exec dev-test-postgres pg_isready -U golfuser >/dev/null 2>&1; then
            echo "✅ Database is ready"
            break
          fi
          echo "Waiting... ($i/30)"
          sleep 2
        done

    - name: Setup Chrome for testing
      run: |
        echo "🌐 Setting up Chrome for headless testing..."
        chmod +x ./setup-chrome-headless.sh
        ./setup-chrome-headless.sh

    - name: Clear npm cache
      run: |
        echo "🧹 Clearing npm cache to prevent path resolution issues..."
        npm cache clean --force
        
    - name: Cache node modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.npm
          frontend/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: |
        echo "📦 Installing frontend dependencies..."
        npm ci --legacy-peer-deps --cache ~/.npm

    - name: Build frontend (development)
      working-directory: ./frontend
      run: npm run build

    - name: Run frontend tests
      working-directory: ./frontend
      run: |
        echo "🧪 Running Angular tests..."
        if command -v google-chrome >/dev/null 2>&1 || command -v chrome >/dev/null 2>&1; then
          echo "✅ Chrome available, running tests"
          npm run test -- --watch=false --browsers=ChromeHeadless
        else
          echo "⚠️  Chrome not available, skipping tests (build verification passed)"
        fi

    - name: Restore .NET dependencies
      working-directory: ./backend
      run: dotnet restore

    - name: Build .NET application
      working-directory: ./backend
      run: dotnet build --no-restore --configuration Debug

    - name: Run backend tests
      working-directory: ./backend
      run: |
        echo "🧪 Checking for .NET tests..."
        TEST_COUNT=$(dotnet test --list-tests --verbosity quiet 2>/dev/null | grep -c "Test Methods" || echo "0")
        if [ "$TEST_COUNT" -gt 0 ]; then
          echo "✅ Running $TEST_COUNT .NET tests"
          dotnet test --no-build --configuration Debug
        else
          echo "⚠️  No .NET tests found, skipping test execution"
          echo "Build verification completed successfully"
        fi
      env:
        ConnectionStrings__DefaultConnection: "Host=localhost;Port=5434;Database=golfdb_test;Username=golfuser;Password=golfpassword"

    - name: Cleanup test database
      if: always()
      run: |
        echo "🧹 Cleaning up test database..."
        docker stop dev-test-postgres || true
        docker rm dev-test-postgres || true

    - name: Development Build Complete
      run: |
        echo "✅ Development build and tests completed successfully!"
        echo "📝 This was a validation build for branch: ${{ github.ref_name }}"
        echo "Ready for merge to main branch."
